### ISSUE TITLE
TESTS_DIR variable does not seem to work

### ISSUE THREAD

**Issue by davidfarr** [joonvena/robotframework-docker-action#6]
It seems regardless of what is given for the directory that the robot test suites/cases are located following the examples here and on your tutorial I get an error message:

`[ ERROR ] Suite 'Tests' contains no tests or tasks.`

If the function is working as expected then an explanation of how to provide a sufficient directory path to the readme would be very helpful.

**Comment by joonvena** [comment]
Hi, i have released new version of the action that uses composite. If you want to try that you could test it out with this:
`
robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
       with:
          robot_tests_dir: 'path to dir that contains the tests'
`

**Comment by lucasfraga-bnex** [comment]
robot_tests_dir is working for me, but:

"Resource file 'any' does not exist." always.
Why?

Thanks!

**Comment by joonvena** [comment]
Could you provide example of your workflow file and if possible also some details about your tests?

**Comment by anaouss** [comment]
Hi @joonvena, @lucasfraga-bnex,

I'm facing the same issue, the suggested solution mentioned above didn't work for me.

**My directory contents :**
├── .github
│   └── workflows
│       └── blank.yml
├── test
     ├── MyLibrary.py
     └── tests.robot

**My code:**

name: Robot Framework

on:
  push:
    branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        name: Run Robot Framework Tests
        steps:
          - uses: actions/checkout@v2
          - name: Execute tests
            uses: joonvena/robotframework-docker-action@v1.0
            with:
              ROBOT_TESTS_DIR: $GITHUB_WORKSPACE/test

Did I miss something?
Thank you in advance ..

**Comment by Ssvenkerud** [comment]
I have the same issue as well, done several experiments and as far as i can tell this traces back to an issue on the [ppodgorsek](https://github.com/ppodgorsek) /
[docker-robot-framework](https://github.com/ppodgorsek/docker-robot-framework) image. 

For completeness I`ll add my action yaml as well.
```

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: acceptance-tests
        uses: joonvena/robotframework-docker-action@v1.0
        env:
          BROWSER: chrome
          ROBOT_TESTS_DIR: ${{ github.workspace }}/tests/acceptance_tests
          ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports
      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/reports

```
